version: '3'
services:
  db:
    platform: linux/amd64
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  server:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/server
    ports:
      - "3000:3000"
    depends_on:
      - db
